### PR TITLE
Major type_class overhaul

### PR DESCRIPTION
**Pull request by expede**
#28 
#26 
#25 
#24 
#20
#19 
#12
#11 (forthcoming)
#7 (forthcoming)

### CODE REVIEW

**Comment by vic** [comment]
thanks you for all your hard (and good quality) work on this. ❤️  reading your code.

**Comment by expede** [comment]
@vic thanks! It's awesome to hear that the effort is appreciated ❤️ Now to find time to actually finish it off 🤔 (It's been a pretty crazy January)

**Comment by ShaneWilton** [comment]
If you'd like, I might be able to pick up the missing pieces. Feel free to ping me on Slack (@shanewilton), if you want to talk over what's left :)

**Comment by expede** [comment]
I've successfully extracted myself from the 90-hour work weeks 🎉  Development will resume shortly.

HOWEVER, if anyone would like to contribute, I'm always happy to accept work from others! Branch off of this (admittedly unstable) branch, and submit a PR! Maybe drop a line in here so that we can coordinate, but I'm good either way.

**Comment by OvermindDL1** [comment]
> I've successfully extracted myself from the 90-hour work weeks 🎉 Development will resume shortly.

Whoo hoo!
I'd been holding off on adding witchcraft and such because of upcoming change may effect things (I'm using an exceptional amount of exceptional at work currently though ^.^ and I keep coming up with suggestions for it but forget to note them down...  >.>)

> HOWEVER, if anyone would like to contribute, I'm always happy to accept work from others! Branch off of this (admittedly unstable) branch, and submit a PR! Maybe drop a line in here so that we can coordinate, but I'm good either way.

Yeah I really need to do PR's instead.  ^.^
My work goes from being super-busy for weeks to super-dead for weeks (yay for being able to work on anything I want), but hit a super-busy time period starting last week.  ^.^;

**Comment by expede** [comment]
Okay! Here's the plan. I'm going to scale back the scope of this. No more profunctor in _this_ PR 😉

- [ ] Scale back
- [ ] Pass tests
- [ ] Docs
- [ ] Instances
- [ ] Update Algae

**Comment by ktec** [comment]
> HOWEVER, if anyone would like to contribute, 

I'd really love to contribute, but honestly this is all a little beyond me atm. I'm working as hard as I can to catch up. Between watching Bartosz etc,  I keep coming back and reading through your code bit by bit trying to absorb and comprehend. I'll keep at it, so hopefully at some point I'll be able to either contribute or just help promote by doing talks about it. One thing for sure, I'm excited about where you're going with this. If there's any opportunity to pair on anything I'd jump at the chance.

**Comment by expede** [comment]
Okay, here's what's happening. This is getting merged as a VERY early alpha. This PR is getting to long to actually read through sensibly. While I don't like merging stuff to master that's unfinished, I need to be able to break out smaller chunks of this to work on.

In terms of _actual work_, I've been working truly insane hours at my day job pretty much since the start of 2017. I've booked off almost all of July, so that is _the absolute latest_ that this will get wrapped up. In front of that, I'm developing a paid [2-day Elixir course at LambdaConf](http://lambdaconf.us/training/lcusc/up-and-running-with-elixir-and-phoenix.html), and that's eating a lot of my time... I'm _itching_ to get this done, and that's the last barrier. Getting there slowly but surely...

**Comment by expede** [comment]
Oh, also should mention that I'm _not_ publishing alpha-1 to Hex.

**Comment by ktec** [comment]
Good luck with the workshop, looks great! Looking forward to July!!

**Pull request merged**
